In [1]:
import torch

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [5]:
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [6]:
df.drop(columns= ['id', 'Unnamed: 32'], inplace=True)

In [7]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [10]:
X_train

array([[-0.28786336,  0.36639904, -0.25430897, ...,  0.04135354,
        -0.57178994, -0.13004704],
       [ 0.54364302, -0.29795704,  0.59607875, ...,  1.08064406,
         2.33008911,  2.29447019],
       [-0.20721558,  0.10855455, -0.25997283, ...,  0.00939878,
        -0.02609388, -0.59849924],
       ...,
       [-0.5353686 ,  0.76129601, -0.56986674, ..., -0.7917527 ,
         0.34110347, -0.11312909],
       [-0.5159019 , -1.57324196, -0.54276114, ..., -0.32673486,
        -0.12299318, -0.94852579],
       [-0.60767351,  1.33041223, -0.59292673, ...,  0.0733083 ,
        -0.51059038, -0.08512697]], shape=(455, 30))

In [11]:
y_train

466    B
34     M
171    M
132    M
184    M
      ..
76     B
243    B
490    B
170    B
445    B
Name: diagnosis, Length: 455, dtype: object

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,

In [14]:
y_test

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0])

In [15]:
## Numpy Arrays to PyTorch tensors

X_train_tensor = torch.from_numpy(X_train)
y_train_tensor = torch.from_numpy(y_train)
X_test_tensor = torch.from_numpy(X_test)
y_test_tensor = torch.from_numpy(y_test)

In [17]:
X_train_tensor.shape

torch.Size([455, 30])

## Defining the Model

In [22]:
class MySimleNN():
    ## Single Neuron
    def __init__(self, X):
        self.W = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.b = torch.zeros(1, dtype = torch.float64, requires_grad=True)
        ## requires_grad means this is to be trained
    
    def forward(self, X):
        z = X @ self.W + self.b
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y_train_tensor):
        ## Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        ## Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

### Hyperparameters

In [23]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [24]:
## creating model
model = MySimleNN(X_train_tensor)
model.b

tensor([0.], dtype=torch.float64, requires_grad=True)

In [27]:
## Training the model

## Repeat(number of epochs)
##      forward pass
##      loss calculation
##      backward pass
##      Parameter Update
for epoch in range(epochs):
    y_pred = model.forward(X_train_tensor)
    loss = model.loss_function(y_pred, y_train_tensor)
    loss.backward()
    with torch.no_grad():
        model.W -= learning_rate * model.W.grad
        model.b -= learning_rate * model.b.grad

    model.W.grad.zero_()
    model.b.grad.zero_()

    print(f'Epoch: {epoch + 1}, Loss: {loss}')

Epoch: 1, Loss: 3.380992319670249
Epoch: 2, Loss: 3.1060008701018984
Epoch: 3, Loss: 2.961069975235558
Epoch: 4, Loss: 2.8156181624705017
Epoch: 5, Loss: 2.669911618318404
Epoch: 6, Loss: 2.5218733665182715
Epoch: 7, Loss: 2.373554786021189
Epoch: 8, Loss: 2.2147060565528154
Epoch: 9, Loss: 2.055918899355596
Epoch: 10, Loss: 1.8986865420588257
Epoch: 11, Loss: 1.7475892589956492
Epoch: 12, Loss: 1.6016937293367883
Epoch: 13, Loss: 1.4652052825582493
Epoch: 14, Loss: 1.3323093471186427
Epoch: 15, Loss: 1.2111874573893553
Epoch: 16, Loss: 1.1067059812877145
Epoch: 17, Loss: 1.0198190640004747
Epoch: 18, Loss: 0.9502996015672505
Epoch: 19, Loss: 0.8968019853136429
Epoch: 20, Loss: 0.8570729692261673
Epoch: 21, Loss: 0.8283233035616376
Epoch: 22, Loss: 0.8077271297780395
Epoch: 23, Loss: 0.7928420598256533
Epoch: 24, Loss: 0.7818006186053462
Epoch: 25, Loss: 0.7732950410138725


In [36]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)

In [37]:
y_pred

tensor([[0.3221],
        [0.2230],
        [0.3457],
        [0.2458],
        [0.5997],
        [0.6974],
        [0.2517],
        [0.4868],
        [0.3028],
        [0.5333],
        [0.3293],
        [0.3656],
        [0.5381],
        [0.6380],
        [0.3033],
        [0.3497],
        [0.4636],
        [0.2479],
        [0.7520],
        [0.6829],
        [0.5326],
        [0.7206],
        [0.6451],
        [0.5256],
        [0.3697],
        [0.4434],
        [0.6500],
        [0.4388],
        [0.4039],
        [0.5650],
        [0.3291],
        [0.5950],
        [0.4572],
        [0.5256],
        [0.2612],
        [0.4190],
        [0.3189],
        [0.3556],
        [0.4932],
        [0.3620],
        [0.7097],
        [0.4075],
        [0.2686],
        [0.3671],
        [0.6462],
        [0.2728],
        [0.5106],
        [0.7556],
        [0.2990],
        [0.2851],
        [0.9662],
        [0.4751],
        [0.2594],
        [0.6202],
        [0.2472],
        [0

In [38]:
y_test_tensor

tensor([0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0])

In [39]:
y_pred = (y_pred > 0.5).float()

In [40]:
y_pred

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
      

In [41]:
accuracy = (y_pred == y_test_tensor).float().mean()

In [42]:
accuracy

tensor(0.5409)