In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f'Using GPU: {torch.cuda.get_device_name(0)}')
else:
    print("GPU not available, using CPU")

GPU is available!
Using GPU: Tesla T4


### Creating a Tensor

In [ ]:
torch.empty((2, 3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
a = torch.zeros(4, 5)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.ones_like(a)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
torch.rand(9)
## Each coordinate is a random value uniformly selected from [0, 1)

tensor([0.5911, 0.2816, 0.1525, 0.1234, 0.1048, 0.9440, 0.8068, 0.3916, 0.2965])

In [ ]:
torch.manual_seed(9) ## Setting the seed
torch.rand_like(a)

tensor([[0.6558, 0.3020, 0.4799, 0.7774, 0.9180],
        [0.9310, 0.2604, 0.9534, 0.3804, 0.4104],
        [0.9510, 0.5686, 0.1381, 0.2069, 0.5139],
        [0.4850, 0.5193, 0.3468, 0.4477, 0.6316]])

In [ ]:
torch.tensor([[2, 3, 4], [5, 6, 7]])

tensor([[2, 3, 4],
        [5, 6, 7]])

In [ ]:
torch.arange(0, 10, 0.5) ## Jump is last arg

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])

In [ ]:
torch.linspace(0, 20, 5) ## Size is last arg

tensor([ 0.,  5., 10., 15., 20.])

In [ ]:
torch.eye(5) ## Identity

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((10, 9, 3), 2)
## Give the dimensions and the value to be filled at ALL coordinates

tensor([[[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [2, 2, 2],
         [

### Tensor Shapes

In [ ]:
x = torch.tensor([[1, 2, 4], [2, 4, 8]])

In [ ]:
torch.rand_like(x)
## Because datatype of x is int, but rand has outputs that are float/long

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
x.dtype

torch.int64

In [ ]:
y = torch.tensor([[1, 2, 4], [2, 4, 8]], dtype=torch.float32)

In [ ]:
torch.rand_like(y)

tensor([[0.6947, 0.8215, 0.9111],
        [0.7315, 0.4468, 0.0725]])

In [ ]:
## Changing dtype of an existing tensor
x.to(torch.float32) ## Does not do it inplace

tensor([[1., 2., 4.],
        [2., 4., 8.]])

In [ ]:
x

tensor([[1, 2, 4],
        [2, 4, 8]])

In [ ]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.3567, 0.7719, 0.0121],
        [0.1186, 0.8091, 0.9718]], dtype=torch.float64)

### Operations on Tensors

In [ ]:
x = torch.rand([2,2])

In [ ]:
x ** 2

tensor([[0.6747, 0.2367],
        [0.8801, 0.0272]])

In [ ]:
## Addition/Subtraction/Multiplication etc can be perfomed element-wise
## NumPy like broadcasting
x - 1

tensor([[-0.1786, -0.5134],
        [-0.0618, -0.8349]])

In [ ]:
torch.abs(x - 1)

tensor([[0.1786, 0.5134],
        [0.0618, 0.8349]])

In [ ]:
torch.round([[1.2, 2], [3.3, 4]]) ## Needs torch.tensor input

TypeError: round(): argument 'input' (position 1) must be Tensor, not list

In [ ]:
torch.round(torch.tensor([[1.2, 2], [3.3, 4]]))
## Similarly ceil, floor

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
## torch.clamp (Bounds values by an upper limit and a lower limit, and clips them)
torch.clamp(x, max = 1, min =0.5)

tensor([[0.8214, 0.5000],
        [0.9382, 0.5000]])

### Reduction Operations

In [ ]:
e = torch.randint_like(x, low = 0, high = 10)
e

tensor([[7., 5.],
        [4., 3.]])

In [ ]:
# sum
torch.sum(e)

## similarly .mean(), .median(), .max(), .min(), .prod(), .std(), .var(), .argmax()

tensor(19.)

In [ ]:
torch.sum(e, dim = 1) ## Over rows, vary the index of dimension dim and sum

tensor([12.,  7.])

In [ ]:
torch.argmin(e)

tensor(3)

In [ ]:
torch.matmul(x, y)

tensor([[1.7946, 3.5891, 7.1782],
        [1.2683, 2.5366, 5.0731]])

In [ ]:
x @ y

tensor([[1.7946, 3.5891, 7.1782],
        [1.2683, 2.5366, 5.0731]])

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([2, 3, -2])

In [ ]:
torch.dot(a, b)

tensor(2)

In [ ]:
a @ b

tensor(2)

In [ ]:
x.T

tensor([[0.8214, 0.9382],
        [0.4866, 0.1651]])

In [ ]:
torch.transpose(x, 0, 1) ## Arguments are swapping dimensions

tensor([[0.8214, 0.9382],
        [0.4866, 0.1651]])

In [ ]:
torch.det(x)

tensor(-0.3209)

In [ ]:
torch.inverse(x)

tensor([[-0.5144,  1.5163],
        [ 2.9236, -2.5598]])

In [ ]:
x_t = x.T

In [ ]:
x > x_t

tensor([[False, False],
        [ True, False]])

### Special Functions

In [ ]:
k = torch.randint(size = (5, 3), low = -5, high = 5)

In [ ]:
torch.log(k)

tensor([[0.6931, 0.0000,    nan],
        [0.6931,    nan,    nan],
        [   nan,   -inf,    nan],
        [0.6931,   -inf, 0.6931],
        [   nan, 0.0000,    nan]])

In [ ]:
torch.exp(k)

tensor([[7.3891e+00, 2.7183e+00, 4.9787e-02],
        [7.3891e+00, 1.8316e-02, 6.7379e-03],
        [1.8316e-02, 1.0000e+00, 4.9787e-02],
        [7.3891e+00, 1.0000e+00, 7.3891e+00],
        [6.7379e-03, 2.7183e+00, 4.9787e-02]])

In [ ]:
torch.sqrt(k)

tensor([[1.4142, 1.0000,    nan],
        [1.4142,    nan,    nan],
        [   nan, 0.0000,    nan],
        [1.4142, 0.0000, 1.4142],
        [   nan, 1.0000,    nan]])

In [ ]:
torch.sigmoid(k)

tensor([[0.8808, 0.7311, 0.0474],
        [0.8808, 0.0180, 0.0067],
        [0.0180, 0.5000, 0.0474],
        [0.8808, 0.5000, 0.8808],
        [0.0067, 0.7311, 0.0474]])

In [ ]:
torch.softmax(k.to(float), dim = 0)

tensor([[3.3296e-01, 3.6463e-01, 6.5985e-03],
        [3.3296e-01, 2.4569e-03, 8.9302e-04],
        [8.2532e-04, 1.3414e-01, 6.5985e-03],
        [3.3296e-01, 1.3414e-01, 9.7931e-01],
        [3.0362e-04, 3.6463e-01, 6.5985e-03]], dtype=torch.float64)

In [ ]:
torch.relu(k)

tensor([[2, 1, 0],
        [2, 0, 0],
        [0, 0, 0],
        [2, 0, 2],
        [0, 1, 0]])

### Inplace Operations

In [ ]:
m = torch.rand(2, 3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6235, 0.3730, 0.8572],
        [0.5366, 0.0363, 0.4987]])
tensor([[0.4254, 0.2376, 0.9284],
        [0.5906, 0.3453, 0.0070]])


In [ ]:
m.add_(n) ## In-place version of add, saves result in m

tensor([[1.0489, 0.6106, 1.7856],
        [1.1272, 0.3816, 0.5057]])

In [ ]:
m -= 1

In [ ]:
m.relu_()

tensor([[0.0489, 0.0000, 0.7856],
        [0.1272, 0.0000, 0.0000]])

### Copying a Tensor

In [ ]:
a = torch.rand(1, 2, 3)

In [ ]:
a

tensor([[[0.9552, 0.1192, 0.5466],
         [0.8069, 0.0749, 0.6649]]])

In [ ]:
b = a ## BY REFERENCE!!!

In [ ]:
b[0][1] = 1

In [ ]:
a

tensor([[[0.9552, 0.1192, 0.5466],
         [1.0000, 1.0000, 1.0000]]])

In [ ]:
id(a) ## Memory Location of a

138433146565840

In [ ]:
id(b)

138433146565840

In [ ]:
b = a.clone() ## Function to copy

In [ ]:
id(a)

138433146565840

In [ ]:
id(b)

138433146561808

In [ ]:
a[0][0][0] = 10

In [ ]:
b

tensor([[[0.9552, 0.1192, 0.5466],
         [1.0000, 1.0000, 1.0000]]])

### Tensor Operations on GPU

In [ ]:
device = torch.device('cuda')

In [ ]:
device

device(type='cuda')

In [ ]:
## creating a new tensor on GPU
torch.rand((3, 4), device = device)

tensor([[0.8420, 0.6347, 0.2247, 0.8517],
        [0.9473, 0.5769, 0.6793, 0.0821],
        [0.1950, 0.6674, 0.2915, 0.7639]], device='cuda:0')

In [ ]:
a

tensor([[[10.0000,  0.1192,  0.5466],
         [ 1.0000,  1.0000,  1.0000]]])

In [ ]:
## Moving a tensor to GPU
b = a.to(device)

In [ ]:
b + 5

tensor([[[15.0000,  5.1192,  5.5466],
         [ 6.0000,  6.0000,  6.0000]]], device='cuda:0')

In [ ]:
import time

size = 10000

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

start_time = time.time()
result_cpu = matrix_cpu1 @ matrix_cpu2
cpu_time = time.time() - start_time

print(f'Time on CPU: {cpu_time:.4f} sec')


matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_gpu = matrix_gpu1 @ matrix_gpu2
torch.cuda.synchronize() ## Ensuring all GPU operations are complete
gpu_time = time.time() - start_time

print(f'Time on GPU: {gpu_time:.4f} sec')
print(f'Speedup = {cpu_time/gpu_time}')

Time on CPU: 16.1132 sec
Time on GPU: 0.5157 sec
Speedup = 31.2432108079721


### Reshaping Tensors

In [ ]:
a = torch.zeros((8, 1, 2))

In [ ]:
a.reshape(16)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a.flatten()

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a

tensor([[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]],

        [[0., 0.]],

        [[0., 0.]],

        [[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]])

In [ ]:
a.reshape((2, -1))

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
## Permuting
a.permute(2, 0, 1).shape

torch.Size([2, 8, 1])

In [ ]:
## unsqueeze: adds a new dimension
c = torch.rand(226, 226, 3)
c.unsqueeze(1).shape ## arg is where do you want the new dim

torch.Size([226, 1, 226, 3])

In [ ]:
## squeeze: reduces a dim where 1 was present
d = torch.rand(1, 20)

In [ ]:
d.squeeze(0)

tensor([0.6303, 0.0639, 0.1469, 0.0382, 0.4907, 0.0673, 0.7226, 0.5286, 0.5670,
        0.7752, 0.0593, 0.6092, 0.3009, 0.8276, 0.6596, 0.6307, 0.9589, 0.2267,
        0.2704, 0.1168])

In [ ]:
d.squeeze(1) ## Nothing Happened

tensor([[0.6303, 0.0639, 0.1469, 0.0382, 0.4907, 0.0673, 0.7226, 0.5286, 0.5670,
         0.7752, 0.0593, 0.6092, 0.3009, 0.8276, 0.6596, 0.6307, 0.9589, 0.2267,
         0.2704, 0.1168]])

## Numpy <=> Torch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor((3,4,2))

In [ ]:
b = a.numpy()

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])